mggg/GerryChainJulia

src/GerryChain.jl
test/graph.jl
test/recom.jl
test/runtests.jl

* Figured out how to test unexported Package functions (use GerryChain.funcName when calling those functions)
* Moved dependencies (like DataStructures.jl) from runtests.jl to only the test files that uses them. Cleaner for namespace reasons, and forces more intent from the programmer writing tests.

package doesn't export private recom functions

---

src/GerryChain.jl
src/accept.jl
src/flip.jl
src/partition.jl
src/recom.jl
test/accept.jl
test/runtests.jl

In this PR, I implement functionality that allows the user to pass in a custom acceptance function to `recom_chain` and `flip_chain.` Acceptance functions allow users to compare an updated partition (i.e., the next step in the chain) to the original partition and decide a probability with which to accept or reject the updated partition. (The probability may be 0 or 1). If the new partition is rejected, the step counter is incremented and the new partition is discarded (i.e., a self-loop in the Markov chain).
- `src/accept.jl` contains a standard acceptance function, `always_accept`, as well as `pass_acceptance_fn`, which takes in the user function for generating the acceptance probability, runs a single Bernoulli trial with that probability, and returns `true` or `false`. I implement …

Custom acceptance functions

---

src/constraints.jl
src/partition.jl
src/recom.jl
test/flip.jl
test/recom.jl

- Add two unit tests that run 2 steps of a recom/flip chain
- Remove global RNG; allow user option to pass in their own RNG - otherwise, default to `Random.default_rng()`

Add very basic unit tests for recom_chain and flip_chain and remove global RNG 

---

src/GerryChain.jl
src/flip.jl
src/recom.jl
src/scores.jl
test/flip.jl
test/recom.jl
test/scores.jl

At long last, I've taken a stab at implementing separate classes for district and partition-level functions! At a high level, here is how a user would instantiate an array of `Score`s that could then be passed into `flip_chain`/`recom_chain`:
```
scores = [
DistrictAggregate("presd", "PRES12D"), # DistrictAggregate are akin to what used to be "node_attrs" - simple sums over the value of a property for all nodes in a district
DistrictAggregate("WHITE_POP"), # by default, if only one argument is passed in, the key and name are the same
DistrictScore("myDistrictLevelScore", fn), # fn should take a graph::BaseGraph and nodes::BitSet as arguments
PlanScore("myPartitionLevelScore", fn2), # fn2 should take a graph::BaseGraph and partition::Partition as arguments
]
```
The return values of …

Implemented framework for district & partition-level score functions

---

test/scores.jl

- Remove redundant scores passed in a test (the `DistrictAggregate` scores that are removed are already part of a `CompositeScore` in the same `scores` array)
- Add a test for cut edges & districts changed after a proposal

Clean up tests in scores.jl

---

src/GerryChain.jl
src/scores.jl
test/scores.jl

`flip_chain` and `recom_chain` return an array of Dicts that is optimized to save space by only saving information for scores that have changed at each proposal step. However, in order to analyze / plot / visualize the scores of the plans in the ensemble, there needs to be an easy way to extract all the values of the particular score(s) throughout the chain.
In this PR, I implement `get_score_values`, a function that produces an array/matrix of score values that can easily be passed into plot/visualization/summary statistic functions. The function takes in an array of `Dict`s (i.e., the return value of `flip_chain` and `recom_chain`) and an arbitrary `AbstractScore`. I take advantage of multiple dispatch to implement the method differently depending on whether a `DistrictAggregate`, …

Allow user to easily extract all values of scores at all steps in the chain

---

src/GerryChain.jl
src/flip.jl
src/recom.jl
src/scores.jl
test/scores.jl

This PR introduces a new type, `ChainScoreData`, which is the new return type for `recom_chain()` and `flip_chain()`. This object stores both the score functions that were measured on every plan in the chain as well as the values of the scores at every step of the chain. Introducing this new type has several benefits:
- We no longer are passing around this complex `Array{Dict{String, Any}}` object whose structure is understood only by us
- Users can now pass in the string names of scores to `get_scores_at_step` and `get_score_values` (rather than the `AbstractScore` object itself), and we can still take advantage of very clean multiple dispatch behind the scenes to handle cases where the scores requested are `DistrictScore`s vs `PlanScore`s vs `CompositeScore`s
```
scores = [ …
```

ChainScoreData type

---

src/GerryChain.jl
src/election.jl
src/scores.jl
test/election.jl
test/scores.jl

(See issue #25.) Also, **N.B.**: I've added a lot of explanatory comments, because I suspect this PR may be hard to parse!
Currently, the `ElectionTracker` object has a `DistrictScore` baked in that recalculates vote counts & vote shares for every party. This `DistrictScore` both updates the `Election` object as well as returns a `Dict` that maps party name to a tuple of vote count & vote share won by that party in a particular district. This is non-ideal, and also makes it difficult for users to easily extract the values of vote count/vote share by party from the object returned by `recom_chain()` / `flip_chain`. Furthermore, it gave no way for the user to only track vote count/share for a particular party of interest, instead forcing the user to record outcomes for all parties.
This PR …

Add simple vote scores

---

.travis.yml

Allow the nightly build to fail because it is unstable. This is what the build looks like right now, note the "This job is allowed to fail".
Also added a code coverage tool `codecov`.

Allow nightly fail

---

README.md

Woops forgot to add the badge to the README, which I have fixed now.

add codecov badge in README

---

src/GerryChain.jl
src/plot.jl
test/plot.jl

This PR makes it easy for the user to create a histogram of the values of a partition-level score throughout all steps of the chain. Also allows the user to pass in the score of particular plan(s) that they can see plotted against the histogram of the chain's score values!
```
score = [ DistrictScore("hispanic_pop", calculate_hispanic_pop, PlanScore("cut_edges", count_cut_edges) ]
enacted_hispanic_pops = [323, 231, 492, 2391...]
enacted_cut_edges = 400
chain_data = recom_chain(...)
score_histogram(chain_data, "cut_edges", comparison_scores=[ ("enacted", 21) ]) # if the enacted plan has 21 cut edges
plt.ylabel("Number of Cut Edges")
```
(Inspiration from the [MGGG Alaska report](https://mggg.org/uploads/Alaska.pdf), Figure 12 on page 27)
**PROMISE**: I will update documentation once this …

User-facing tool for plotting plan scores on histogram 

---

src/graph.jl
test/graph.jl
test/runtests.jl

(This PR depends on #34.)
Now that we've implemented queen/rook adjacency, we can add a method that actually determines whether there is any intersection between two geographical units in the shapefile. This will be used to construct a complete `SimpleGraph` of edges and nodes.

Create simple graph from polygons

---

src/graph.jl
src/partition.jl
test/graph.jl

(Depends on #35.)
This PR finally allows a user to use `BaseGraph("path/to/example.shp", POPULATION_COL, ASSIGNMENT_COL)` to instantiate a `BaseGraph` object. I also reorganize the code with three new functions (`adjacency_matrix_from_graph`, `neighbors_from_graph`, and `edges_from_graph`) that are now shared between `graph_from_json` and `graph_from_shp` (yay for non-redundancy!)

Create BaseGraph from .shp

---

src/scores.jl

On my merry way to allowing users to store scores from the chain in a CSV object, I realized that I should create an iterator, where each "step" of the iterator yields a dictionary of score values at the corresponding step of the chain. This is helpful because I already kind of do that in `get_scores_at_step` and didn't want to copy/paste the code into `save_scores`. This iterator is only intended to be used internally, but if you all think it's a good API, I can also expose it to the user.
```
chain_data = recom_chain(...) # pretend there's a district score called "NumPurples" and PlanScore called "cut_edges"
score_query = ChainScoreQuery(["NumPurples", "cut_edges"], chain_data)
for score_dict in score_query
end
```

ChainScoreQuery iterator

---

src/graph.jl
src/partition.jl
test/accept.jl
test/constraints.jl
test/election.jl
test/flip.jl
test/partition.jl
test/recom.jl
test/scores.jl

(Depends on #36.)
Since all the node attributes are stored in the `BaseGraph` object, there is no need for the `Partition` object to require that the user pass in a path to a `JSON` file. I alter the `Partition` constructor to only require the `BaseGraph` and the string key for the assignment attribute. Now we can finally run chains using Shapefiles! 🎊🎊🎊
```
graph = BaseGraph("./UT_precincts/UT_precincts.shp", "TOTPOP", "CountyID")
partition = Partition(graph, "CountyID")
...
chain_data = recom_chain(graph, partition, pop_constraint, 10, scores)
```
* Removing `get_populations_and_assignments` and replacing with a more general `get_attribute_by_key` method
* Alter `Partition` constructor 
* Modify tests now that the `Partition` constructor has changed
**PROMISE**: I will update the …

Change API for Partition constructor to only require a BaseGraph and assignment column

---

src/election.jl
src/scores.jl
test/scores.jl

(This PR is designed to address #30, exposition copied/edited below). 
Some AbstractScores are meant to return values that get stored in the object returned by flip_chain / recom_chain. Others are simply meant to run every time a proposal is accepted (and do not return anything; e.g., the `vote_updater` function for the `ElectionTracker`. As a result, our `score_initial_partition` and `score_partition_from_proposal` functions (which return a `Dict` mapping score keys to score values) manually check whether the return type of a function is `nothing` before recording it in a `Dict`. This is messy and hard to read. Instead, these types of scores should be somehow clearly delineated in our codebase, rather than manually checking if the return type is `nothing`, which gets quite expensive.
(As …

Do not save scores with uninitialized names

---

Project.toml
src/GerryChain.jl
src/scores.jl

(N.B. This PR depends on #40 and #39, so the branch I'm asking to merge into is a Frankenstein of PR #39 and #40 so that the commit history of this PR looks right. I'll be sure to double check when I merge things into `main` that I don't run into any weird git errors.)
This method allows the user to easily save the scores of their choosing in a file with a CSV format. The main issue with saving as a JSON was that (a) we were saving the delta score format (which no one understands besides us) and (b) if we wanted to save the raw value of every score at every step, we would have to load all those values into RAM...which defeats the purpose of the delta score.
Enter CSVs! We can write to a CSV line by line, so we only have to be able to load in the score values for a particular state of the …

Save scores as csv

---

src/GerryChain.jl
src/scores.jl
test/scores.jl

Pretty self-explanatory! This PR will allow us to close #25. It adds an easy-to-use function where users pass in a `String` representing the name of the score and a `PlanScore` is returned.
```
scores = [
...
num_cut_edges("cut_edges")
]
data = recom_chain(..., scores)
```
**PROMISE**: I will update the documentation to include this new score soon!

Add simple score to count number of cut edges

---

src/graph.jl
test/graph.jl

This PR closes #50.
As per @pjrule's [comment](https://github.com/mggg/GerryChainJulia/pull/31#discussion_r462471026) on a previous PR, the way GerryChain currently attempts to read in a shapefile is by first trying to read it as a JSON, then trying to read it as a .shp file, and then rejecting if both fail. While this approach is clean, the way it is implemented now unfortunately can generate some confusing error messages for the user (see the "Before" picture that shows the full error output when the user attempts to read from a shapefile but the assignment column has the wrong type.)
In this PR, I change the `BaseGraph` function so that it explicitly checks the extension before attempting to read the shapefile. 
(Note how the core error - the type of the assignment column - is buried …

Modify how error handling works for reading in JSON/.shp files to be more user-friendly

---

src/graph.jl
test/graph.jl

(See Issue #51 for more context.)
Currently, when users read in a JSON, we check if the assignment column is an `Int` or a `String` and parse it appropriately. *However*, when it is *neither an `Int` nor a `String`, we don't emit any error and instead just store all the assignments as `0`! This is definitely wrong and users have fed in shapefiles to the `BaseGraph` constructor method unaware that the type of the assignment column was wrong and then been confused as to why their code was hitting an error.

Throw error when assignment column could not be processed

---

src/plot.jl

Currently, we only allow the user to pass in an `Int` for the `bins` param of `score_histogram`. In this PR, we allow them to pass in a `Vector` as well, which is often used when users want flexibility over the exact boundaries of the histogram bars (e.g., having the bars centered on discrete values when plotting a histogram of counts).
```
score_histogram(chain_data, "efficiency_gap", rwidth=1, bins=collect(-0.025:0.025:0.150), comparison_scores=[("mean", 0.1), ("mean2", 0.06)])
```
**PROMISE**: I will update documentation to show this before merging!

Allow user to pass in array for bins in plot_histograms

---

.github/workflows/TagBot.yml
Project.toml

I added a config file for the TagBot, which should help us keep track of the release versions (https://github.com/marketplace/actions/julia-tagbot)
Also, I added a bunch of  compatibility upper bound versions because the Julia registry is not letting me register unless I do that, with this specific fail message: 
`The following dependencies do not have a compat entry that has an upper bound: DataStructures, JSON, LibGEOS, LibSpatialIndex, LightGraphs, PyPlot, Shapefile, julia. `
(https://github.com/JuliaRegistries/General/pull/20341)
My hope is that this PR will allow the package to be auto-merged, as well as set up the tag bot.

Add tagbot

---

README.md

Addresses #72 .
Simply pointing the Travis build icon to the `main ` branch instead of whatever dev branch was pushed latest.

point build icon to main branch

---

src/graph.jl
test/graph.jl

Turns out `induced_subgraph_edges()` was returning _duplicated_ edges ie if the expected return value was [3, 4, 5] it would return [3, 3, 4, 4, 5, 5]. 
This is because of the way we loop over the adjacency list (see lines 318-325 in `src/graph.jl`. 
This PR fixes this issue, and adds a test for it. 
Additionally, this bug might be why we might occasionally be having chain hanging issues, but I haven't thought hard about that yet.

fix duplicate induced edges bug

---

src/constraints.jl
test/constraints.jl
test/flip.jl
test/plot.jl
test/recom.jl

There is an unused `population_col` argument in `PopulationConstraint` that was living in our codebase rent-free and it simply was time for it to go.

Remove unused population_col argument from PopulationConstraint

---

src/constraints.jl
src/graph.jl
src/partition.jl
src/recom.jl
src/scores.jl
test/accept.jl
test/constraints.jl
test/election.jl
test/flip.jl
test/graph.jl
test/partition.jl
test/plot.jl
test/recom.jl
test/scores.jl

This PR removes the requirement for BaseGraph to take an `assignment` argument. This issue has been brought up in the past -- "Why is BaseGraph and Partition both taking the assignment column, isn't it enough to pass it into just one?". In removing the `assignment` argument requirement from BaseGraph it makes the code more elegant. 
Previous usage:
```
graph = BaseGraph(filepath, POP_COL, ASSIGNMENT_COL)
partition = Partition(graph, ASSIGNMENT_COL)
```
New usage:
```
graph = BaseGraph(filepath, POP_COL)
partition = Partition(graph, ASSIGNMENT_COL)
```
This change was actually forced, in my opinion, by me trying to add the functionality of adding seed partition generating methods. In a non-trivial number of occasions at the lab we work with shapefiles without assignments and we generate a …

Remove assignment col arg from BaseGraph

---

src/GerryChain.jl
src/scores.jl
test/runtests.jl
test/scores.jl

This PR closes issue #48. 
This PR is smaller than it looks, I promise! The function `save_scores` has now been renamed `save_scores_to_csv` and there is a new function called `save_scores_to_json` (which is really tiny) that saves the scores in a chain to a JSON file. Each state of the chain is written as a row in the JSON file. 
```
chain_data = recom_chain(graph, partition, pop_constraint, 10, scores)
save_scores_to_json("test.json", chain_data) # by default will save all scores in the chain
```
**PROMISE:** I will update documentation to reflect these changes.

Save scores row-by-row to JSON file

---

src/flip.jl
src/recom.jl
test/flip.jl
test/recom.jl

As discussed with @pjrule , I am putting in a PR that allows the user to easily specify whether a failure to accept should constitute a self-loop (which counts towards the total # of steps) or whether self-loops should be disallowed (i.e., new proposals are generated until one satisfies an acceptance loop, at which point the step counter is incremented). Note that this feature has the potential to create infinite loops, if the user specifies `no_self_loops=true`. 
```
chain_data = recom_chain(graph, partition, pop_constraint, num_steps, scores, acceptance_fn=f, no_self_loops=true)
```
**PROMISE**: I will update documentation before merging this code!

Add option to skip self loops for acceptance functions

---

src/plot.jl
test/plot.jl

Following up on an earlier discussion, I convert all calls to `plt` to explicitly taking in an optional matplotlib `Axis` object (or creating one, if the user doesn't pass one in). This is a more common pattern that aligns with other plotting libraries that use matplotlib under the hood. I also explicitly return the `ax` object to the user.
Functionally, the usage for the user doesn't change much. Users can now do this:
```
_, ax = plt.subplots()
score_histogram(chain_data, "e_gap", ax=ax)
```
```
plan1_bwratios = rand(18)
plan2_bwratios = rand(18)
ax = score_boxplot(chain_data, "dem_vote_share", comparison_scores=[("plan1", plan1_bwratios), ("plan2", plan2_bwratios)])
ax.legend(bbox_to_anchor=(0.5, 0.5))
ax.set_ylabel("Democratic vote share")
```
**PROMISE**: I will update the …

Consistently use ax object in plotting functions

---

src/scores.jl
test/scores.jl

This PR is to address #68. When the `score_fn` errors out from within, the error message was still `PlanScore function must accept graph and partition.` and this was very confusing because graph and partition were actually passed in. The following picture illustrates this issue:
The behavior we actually want is this: If the function does not take a `BaseGraph` and `Partition` as args then we want to emit that error message, but if the user has messed up the function themself then we want Julia's own engine to error out and point to the specific line. 
With the help of the nifty [applicable()](http://www.jlhub.com/julia/manual/en/function/applicable) function, this can be achieved with minimal change.
After the fix we see the following behavior when there is an error within the user's …

make error msg on eval_on() funcs better

---

README.md
docs/src/index.md

Simply updated the doc-badges to README and then updated Zenodo link on README again.
Also added those badges to the index page of the documentation, but this will only get deployed next release.

Doc badges

---

.travis.yml

We let the nightly builds fail anyway, and it annoys me how long it takes to run the tests. 
Also, Travis is taking away credits for this runtime now, so for the timebeing...

remove nightly builds

---

src/scores.jl
test/scores.jl

Bug fix.
Bug:
Previously, if there was a MethodError inside a DistrictScore, the program would give the message "DistrictScore function must accept graph, array of nodes, and district index." which was not true, we would want the Julia engine to error out instead. This bug was introduced by me in #81 when I put in a line copied from the PlanScore function. Sadly, the tests did not catch it because the test was also "templated" from the PlanScore case. 
Fix: 
Now the error is actually from the Julia engine, as expected!

fix bug that gives correct error for wrong DistrictScore argument

---

src/election.jl
test/election.jl

Ari from Princeton was running into this issue where the `vote_counts` in his shapefile were floats, but GerryChain expected it to be `Int` in the definition of the `Election` struct.
I think vote counts should be allowed to be Floats, especially since they might need to be pro-rated to lower geographical units. 
This PR makes that change, and also changes the `wasted_votes()` function and corresponding tests that expected `vote_counts` to be `Int`s.

change vote counts to be floats

---

.github/workflows/test.yml
src/balance_edges.jl
src/recom.jl

One of the reasons why we only get constant scores in some chains is because of a different bug, which is caused by `random_kruskal_mst` being re-seeded with the same static seed (`1234`) every time it is called. In some cases, when combined with other strange behavior that needs to be chased down, this results in a totally deterministic step function -- the chain never takes more than one step because every proposal is the same. This issue has been partially addressed in this PR.

Ensure that random_kruskal_mst doesn't generate the same spanning tree every time
